// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDzbl8itSIDmUj6tnaBcNEoI1ZUx7G4SU',
    appId: '1:295705409045:web:1de3935bc2c05f9071801c',
    messagingSenderId: '295705409045',
    projectId: 'medico-7392a',
    authDomain: 'medico-7392a.firebaseapp.com',
    storageBucket: 'medico-7392a.appspot.com',
    measurementId: 'G-VPF06WL9DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA356B0HcU_ETjGhZ2g55Bmi14gHxFP0Kg',
    appId: '1:295705409045:android:58d57dfbc375d60c71801c',
    messagingSenderId: '295705409045',
    projectId: 'medico-7392a',
    storageBucket: 'medico-7392a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY1r6sRchCrhTyYurNZuQgSdfuQeL4G0g',
    appId: '1:295705409045:ios:32b5f6d43327bda971801c',
    messagingSenderId: '295705409045',
    projectId: 'medico-7392a',
    storageBucket: 'medico-7392a.appspot.com',
    iosClientId: '295705409045-5vpvrljqs7p5mgm5illacmqicmebv0ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.medico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY1r6sRchCrhTyYurNZuQgSdfuQeL4G0g',
    appId: '1:295705409045:ios:32b5f6d43327bda971801c',
    messagingSenderId: '295705409045',
    projectId: 'medico-7392a',
    storageBucket: 'medico-7392a.appspot.com',
    iosClientId: '295705409045-5vpvrljqs7p5mgm5illacmqicmebv0ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.medico',
  );
}
